name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
  FUNCTION_NAME: ${{ secrets.GCP_FUNCTION_NAME }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug environment variables
      run: |
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
        echo "BUCKET_NAME: ${{ env.BUCKET_NAME }}"
        echo "FUNCTION_NAME: ${{ env.FUNCTION_NAME }}"
        echo "REGION: ${{ env.REGION }}"

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy public folder to GCS
      run: |
        gsutil -m rm -rf gs://${{ env.BUCKET_NAME }}/* || echo "$?"
        gsutil -m cp -r public/* gs://${{ env.BUCKET_NAME }}/

    - name: Deploy Cloud Function
      run: |
        cd functions
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --runtime nodejs18 \
          --trigger-http \
          --allow-unauthenticated \
          --region ${{ env.REGION }} \
          --source . \
          --entry-point helloWorld