name: Deploy to GCP

on:
  push:
    branches:
      - main  # or your default branch name

env:
  BUCKET_NAME: myprepv2-devfes  # Your GCP bucket name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GCP
      run: |
        gsutil -m rsync -d -r ./public gs://${{ env.BUCKET_NAME }}
        gsutil iam ch allUsers:objectViewer gs://${{ env.BUCKET_NAME }}

    - name: Set website configuration
      run: |
        gsutil web set -m index.html -e 404.html gs://${{ env.BUCKET_NAME }}

    - name: Print website URL
      run: |
        echo "Your website is now available at: https://storage.googleapis.com/${{ env.BUCKET_NAME }}/index.html"