name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
  REGION: ${{ secrets.REGION }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Verify gcloud configuration
      run: |
        gcloud config list
        gcloud projects list

    - name: Deploy static files to GCS
      run: |
        gsutil -m rm -rf gs://${{ env.BUCKET_NAME }}/* || echo "$?"
        gsutil -m cp -r public/* gs://${{ env.BUCKET_NAME }}/

    - name: Deploy Cloud Function
      run: |
        cd functions
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --runtime nodejs18 \
          --trigger-http \
          --allow-unauthenticated \
          --region ${{ env.REGION }} \
          --source . \
          --entry-point helloWorld