name: Deploy to GCP

on:
  push:
    branches:
      - main  # or your default branch name

env:
  BUCKET_NAME: myprepv2-devfes  # Set your bucket name here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: devfestprep1
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCP Bucket
      run: |
        gsutil -m rsync -d -r ./public gs://${{ env.BUCKET_NAME }}
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://${{ env.BUCKET_NAME }}/**/*.html
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://${{ env.BUCKET_NAME }}/**/*.{css,js,jpg,jpeg,png,gif,svg}

    - name: Set website configuration
      run: |
        gsutil web set -m index.html -e 404.html gs://${{ env.BUCKET_NAME }}

    - name: Make bucket public
      run: |
        gsutil iam ch allUsers:objectViewer gs://${{ env.BUCKET_NAME }}

    - name: Print website URL
      run: |
        echo "Your website is now available at: https://storage.googleapis.com/${{ env.BUCKET_NAME }}/index.html"